---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint --strict .
  # ansible-lint
  flake8 --ignore=E501
platforms:
  - name: centos_7
    image: centos:7
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos_8
    image: centos:8
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu_16
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
  - name: ubuntu_18
    image: ubuntu:18.04
    command: /sbin/init
    privileged: True
  - name: debian_buster
    image: debian:buster
    command: /sbin/init
    privileged: True
  - name: debian_stretch
    image: debian:stretch
    command: /sbin/init
    privileged: True
provisioner:
  name: ansible
verifier:
  name: testinfra
