---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint --strict .
  # ansible-lint
  flake8 --ignore=E501
platforms:
  - name: centos-7
    box: centos/7
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
  - name: ubuntu-16
    box: ubuntu/xenial64
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
  - name: ubuntu-18
    box: ubuntu/bionic64
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
  - name: debian-buster
    box: debian/buster64
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
  - name: debian-stretch
    box: debian/contrib-stretch64  # Standard debian/stretch64 had issues: Unable to locate package linux-headers-4.9.0-9-amd64
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
provisioner:
  name: ansible
verifier:
  name: testinfra
